version: '3.8'

services:
  factorial-logger:
    build: .
    container_name: factorial-time-tracker
    environment:
      # Factorial credentials - update these values or use .env file
      - FACTORIAL_EMAIL=${FACTORIAL_EMAIL}
      - FACTORIAL_PASSWORD=${FACTORIAL_PASSWORD}
      - WORK_START_TIME=${WORK_START_TIME:-09:00}
      - WORK_END_TIME=${WORK_END_TIME:-17:00}
      - BREAK_MINUTES=${BREAK_MINUTES:-60}
      - TZ=${TZ:-Europe/Madrid}
      # Cron schedule (default: daily at 18:00)
      - CRON_SCHEDULE=${CRON_SCHEDULE:-0 18 * * *}
      # Browser configuration for headless mode
      - HEADLESS=true
      - DISPLAY=:99
      - NODE_ENV=production
    volumes:
      # Persist logs outside container
      - ./logs:/app/logs
      # Mount .env file if it exists
      - ./.env:/app/.env:ro
    restart: unless-stopped
    # Health check to ensure container is working
    healthcheck:
      test: ["CMD", "pgrep", "cron"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s